[2020-12-11 04:06:16,359] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T13:50:00+00:00 [queued]>
[2020-12-11 04:06:16,405] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T13:50:00+00:00 [queued]>
[2020-12-11 04:06:16,408] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:06:16,410] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 04:06:16,411] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:06:16,423] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T13:50:00+00:00
[2020-12-11 04:06:16,427] {standard_task_runner.py:54} INFO - Started process 3546 to run task
[2020-12-11 04:06:16,507] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T13:50:00+00:00', '--job_id', '430', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmp4dsuk09u']
[2020-12-11 04:06:16,512] {standard_task_runner.py:78} INFO - Job 430: Subtask Importar1
[2020-12-11 04:06:16,613] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T13:50:00+00:00 [running]> d31552e451f4
[2020-12-11 04:06:16,665] {import-dag.py:31} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 04:06:16,666] {import-dag.py:32} INFO - ===== Archivo  =============
[2020-12-11 04:06:16,669] {import-dag.py:33} INFO - time_series_covid19_confirmed_global.csv
[2020-12-11 04:06:16,673] {import-dag.py:34} INFO - ===== Tabla  =============
[2020-12-11 04:06:16,675] {import-dag.py:35} INFO - time_series_covid19_confirmed_global
[2020-12-11 04:06:16,697] {taskinstance.py:1150} ERROR - 'Variable 127.0.0.1 does not exist'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 36, in importarCsv
    host = Variable.get("127.0.0.1")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 117, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable 127.0.0.1 does not exist'
[2020-12-11 04:06:16,720] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar1, execution_date=20201210T135000, start_date=20201211T040616, end_date=20201211T040616
[2020-12-11 04:06:21,344] {local_task_job.py:102} INFO - Task exited with return code 1
