[2020-12-11 00:14:25,782] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [queued]>
[2020-12-11 00:14:25,829] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [queued]>
[2020-12-11 00:14:25,830] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:14:25,831] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 00:14:25,832] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:14:25,848] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T01:00:00+00:00
[2020-12-11 00:14:25,854] {standard_task_runner.py:54} INFO - Started process 559 to run task
[2020-12-11 00:14:25,900] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T01:00:00+00:00', '--job_id', '20', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpvjtagsvi']
[2020-12-11 00:14:25,904] {standard_task_runner.py:78} INFO - Job 20: Subtask Importar1
[2020-12-11 00:14:25,971] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [running]> 7d635893eab6
[2020-12-11 00:14:26,016] {import-dag.py:28} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 00:14:26,019] {import-dag.py:29} INFO - ===== Archivo  =============
[2020-12-11 00:14:26,020] {import-dag.py:30} INFO - time_series_covid19_confirmed_global
[2020-12-11 00:14:26,021] {import-dag.py:31} INFO - ===== Tabla  =============
[2020-12-11 00:14:26,022] {taskinstance.py:1150} ERROR - 'tabla'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 32, in importarCsv
    logger.info(kwargs['tabla'])
KeyError: 'tabla'
[2020-12-11 00:14:26,029] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar1, execution_date=20201210T010000, start_date=20201211T001425, end_date=20201211T001426
[2020-12-11 00:14:30,738] {local_task_job.py:102} INFO - Task exited with return code 1
[2020-12-11 00:26:58,281] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [queued]>
[2020-12-11 00:26:58,332] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [queued]>
[2020-12-11 00:26:58,335] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:26:58,339] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 00:26:58,342] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:26:58,363] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T01:00:00+00:00
[2020-12-11 00:26:58,374] {standard_task_runner.py:54} INFO - Started process 288 to run task
[2020-12-11 00:26:58,413] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T01:00:00+00:00', '--job_id', '42', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmplnbwl01h']
[2020-12-11 00:26:58,417] {standard_task_runner.py:78} INFO - Job 42: Subtask Importar1
[2020-12-11 00:26:58,498] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T01:00:00+00:00 [running]> 7d635893eab6
[2020-12-11 00:26:58,546] {import-dag.py:28} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 00:26:58,547] {import-dag.py:29} INFO - ===== Archivo  =============
[2020-12-11 00:26:58,549] {import-dag.py:30} INFO - time_series_covid19_confirmed_global.csv
[2020-12-11 00:26:58,551] {import-dag.py:31} INFO - ===== Tabla  =============
[2020-12-11 00:26:58,554] {import-dag.py:32} INFO - time_series_covid19_confirmed_global
[2020-12-11 00:26:58,556] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-11 00:26:58,587] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=import-dag, task_id=Importar1, execution_date=20201210T010000, start_date=20201211T002658, end_date=20201211T002658
[2020-12-11 00:27:03,248] {local_task_job.py:102} INFO - Task exited with return code 0
