[2020-12-11 04:33:23,068] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T21:45:00+00:00 [queued]>
[2020-12-11 04:33:23,111] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T21:45:00+00:00 [queued]>
[2020-12-11 04:33:23,113] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:33:23,115] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 04:33:23,117] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:33:23,132] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T21:45:00+00:00
[2020-12-11 04:33:23,136] {standard_task_runner.py:54} INFO - Started process 5766 to run task
[2020-12-11 04:33:23,190] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T21:45:00+00:00', '--job_id', '622', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmphwyfwr73']
[2020-12-11 04:33:23,192] {standard_task_runner.py:78} INFO - Job 622: Subtask Importar1
[2020-12-11 04:33:23,260] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T21:45:00+00:00 [running]> d31552e451f4
[2020-12-11 04:33:23,303] {import-dag.py:31} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 04:33:23,305] {import-dag.py:32} INFO - ===== Archivo  =============
[2020-12-11 04:33:23,310] {import-dag.py:33} INFO - time_series_covid19_confirmed_global.csv
[2020-12-11 04:33:23,312] {import-dag.py:34} INFO - ===== Tabla  =============
[2020-12-11 04:33:23,315] {import-dag.py:35} INFO - time_series_covid19_confirmed_global
[2020-12-11 04:33:23,336] {taskinstance.py:1150} ERROR - 'Variable 127.0.0.1 does not exist'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 36, in importarCsv
    host = Variable.get("127.0.0.1")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 117, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable 127.0.0.1 does not exist'
[2020-12-11 04:33:23,349] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar1, execution_date=20201210T214500, start_date=20201211T043323, end_date=20201211T043323
[2020-12-11 04:33:28,023] {local_task_job.py:102} INFO - Task exited with return code 1
