[2020-12-11 02:33:56,242] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar2 2020-12-10T01:05:00+00:00 [queued]>
[2020-12-11 02:33:56,274] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar2 2020-12-10T01:05:00+00:00 [queued]>
[2020-12-11 02:33:56,276] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:33:56,277] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2020-12-11 02:33:56,278] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:33:56,300] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar2> on 2020-12-10T01:05:00+00:00
[2020-12-11 02:33:56,306] {standard_task_runner.py:54} INFO - Started process 96 to run task
[2020-12-11 02:33:56,364] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar2', '2020-12-10T01:05:00+00:00', '--job_id', '123', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpyiqisye_']
[2020-12-11 02:33:56,367] {standard_task_runner.py:78} INFO - Job 123: Subtask Importar2
[2020-12-11 02:33:56,435] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar2 2020-12-10T01:05:00+00:00 [running]> 12e92ec9b790
[2020-12-11 02:33:56,470] {import-dag.py:31} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 02:33:56,472] {import-dag.py:32} INFO - ===== Archivo  =============
[2020-12-11 02:33:56,473] {import-dag.py:33} INFO - time_series_covid19_deaths_global.csv
[2020-12-11 02:33:56,473] {import-dag.py:34} INFO - ===== Tabla  =============
[2020-12-11 02:33:56,474] {import-dag.py:35} INFO - time_series_covid19_deaths_global
[2020-12-11 02:33:56,487] {taskinstance.py:1150} ERROR - 'Variable 127.0.0.1 does not exist'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 37, in importarCsv
    host = Variable.get("127.0.0.1")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 117, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable 127.0.0.1 does not exist'
[2020-12-11 02:33:56,511] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=import-dag, task_id=Importar2, execution_date=20201210T010500, start_date=20201211T023356, end_date=20201211T023356
[2020-12-11 02:34:01,217] {local_task_job.py:102} INFO - Task exited with return code 1
